Création et manipulation array:

In [3]:
import numpy as np


Objets de type array correspondent à des tableaux à une ou plusierus dimmensions et permmettant de faire du calcul vectoriel. La fonction array() convertit un objet séquentiel comme une liste ou un tuple en un objet de type array.


In [1]:
a = [1,2,3]
np.array(a)

NameError: name 'np' is not defined

In [5]:
b = np.array(a)
b

array([1, 2, 3])

In [6]:
type(b)

numpy.ndarray

In [7]:
a = np.array([1,2,"tigre"]) #comprises comme des chaines de caractères
a

array(['1', '2', 'tigre'], dtype='<U21')

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([1,2,3.4]) #comprises comme des floats
b

array([1. , 2. , 3.4])

arange() permet de créer un tableau simple de une dimension

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

On peut faire des calcul sur les vecteurs grande différence avec les listes

In [13]:
v = np.arange(4)
v

array([0, 1, 2, 3])

In [14]:
v+1

array([1, 2, 3, 4])

In [15]:
v+0.1

array([0.1, 1.1, 2.1, 3.1])

In [16]:
v+2

array([2, 3, 4, 5])

In [17]:
v*v


array([0, 1, 4, 9])

Pour des objets arrays à deux dimensions. il suffit de passer en argument une liste à deux dimensions

In [18]:
np.array([[1,2],[2,3],[5,6]])   # deux dimensions = matrice
                              # 1 dimension = vecteur

array([[1, 2],
       [2, 3],
       [5, 6]])

In [19]:
p = np.array([1,3])
p.ndim

1

In [20]:
m = np.array([[1,2],[2,3],[5,6]])
m.ndim # renvoie la dimension


2

In [21]:
m.shape #renvoie lignes/colonnes

(3, 2)

In [22]:
m.size #renvoie le nombre d'éléments dans le tableau

6

In [23]:
#la méthode reshape() renvoie un nouvel array avec les dimension spécifiées
a = np.arange(0,6)
a


array([0, 1, 2, 3, 4, 5])

In [24]:
b = a.reshape(2,3) #créer un array avec 2 lignes et 3  colonnes
b

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
b.shape

(2, 3)

In [26]:
a

array([0, 1, 2, 3, 4, 5])

In [27]:
a = np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [28]:
a.shape

(6,)

In [29]:
d = a.reshape(3,4) # si il n'y pas assez d'éléments, on ne peut pas changer la config

ValueError: cannot reshape array of size 6 into shape (3,4)

In [30]:
#on peut utliser la fct resize 
a.resize((3,3), refcheck = False) # rajoute des zéros 
a.shape

(3, 3)

In [31]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [0, 0, 0]])

In [32]:
b = np.arange(0,10)
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b.shape

(10,)

In [34]:
b.resize((2,3), refcheck = False) #rajoute des éléments ou coupe le tableau

In [35]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
b.shape

(2, 3)

la modification est faite sur l'objet en question, si refcheck n'est pas présent python peut renvoyer une erreur

In [37]:
a1 = np.array(range(10))
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a2 = np.ones((3,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
print(a2) # attention ressemble à une liste

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [40]:
import random as rd
l = list(range(8))
l

[0, 1, 2, 3, 4, 5, 6, 7]

In [41]:
rd.shuffle(l)
l

[2, 6, 0, 1, 3, 4, 5, 7]

In [42]:
a = np.resize(l,(4,2))
a

array([[2, 6],
       [0, 1],
       [3, 4],
       [5, 7]])

In [43]:
a.max()

7

In [44]:
a.max(axis =0) # compare le plus grand de chaque colonne

array([5, 7])

In [45]:
a.max(axis =1) #compare le plus grand de chaque lignes

array([6, 1, 4, 7])

In [46]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[5:] #prend à partir de 5

array([5, 6, 7, 8, 9])

In [48]:
a[::2] #pas de 2

array([0, 2, 4, 6, 8])

In [ ]:
b = a

In [ ]:
b[2] = 300
a

array([  0,   1, 300,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
c = np.full((2,2),0)
c

array([[0, 0],
       [0, 0]])

In [ ]:
import copy
c = copy.deepcopy(a)
c

array([  0,   1, 300,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
c[0] = 1000000
c

array([1000000,       1,     300,       3,       4,       5,       6,
             7,       8,       9])

In [ ]:
a

array([  0,   1, 300,   3,   4,   5,   6,   7,   8,   9])

In [49]:
np.zeros((5,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((2,2),int)+3

array([[4, 4],
       [4, 4]])

In [ ]:
np.loadtxt("ex.txt",str)

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['h', 'i', 'j']], dtype='<U1')

In [ ]:
#pleins de trucs sur les matrices:


In [52]:
a = np.resize(np.arange(1,10),(3,3))
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
np.dot(a,a) #produit matriciel

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [60]:
a = np.diag((1,2,3)) #diagonale
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [63]:
a = np.reshape(np.arange(1,10),(3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
for row in a:
    print((row),type(row))

[1 2 3] <class 'numpy.ndarray'>
[4 5 6] <class 'numpy.ndarray'>
[7 8 9] <class 'numpy.ndarray'>


In [69]:
for col in a.T:
    print(col, type(col))

[1 4 7] <class 'numpy.ndarray'>
[2 5 8] <class 'numpy.ndarray'>
[3 6 9] <class 'numpy.ndarray'>


In [71]:
np.full((2,2),True)

array([[ True,  True],
       [ True,  True]])

In [73]:
np.full((2,2),False)

array([[False, False],
       [False, False]])

In [130]:
a = np.reshape(np.arange(1,10),(3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
a>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [81]:
(a>3)&(a%2==0)

array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])

In [83]:
a[a>5]

array([6, 7, 8, 9])

In [85]:
a[a == 2]

array([2])

In [87]:
a[a != 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a

array([[1, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

In [131]:
a[a>5]=-1
a

array([[ 1,  2,  3],
       [ 4,  5, -1],
       [-1, -1, -1]])