In [46]:
import numpy as np
print(np.__version__)

1.21.2


In [47]:
a = np.arange(4)
print(a.all())
b = np.arange(4)
print((b.all()))
def fct(tab):
    for i in range(len(tab)-1):
        return True if tab[i] != 0 else False
print(fct(a))
     
     
     

False
False
False


In [40]:
def compare(tab1,tab2):
    return np.array_equal(tab1, tab2, equal_nan=False)
    
print(compare(a,b))

True


In [60]:
def compare2(tab1,tab2):
    return np.allclose(tab1,tab2,rtol=1e-05, atol=1e-08, equal_nan=True)

print(compare(a,b))

False


In [48]:
np.array([1, 7, 13, 105])

array([  1,   7,  13, 105])

In [53]:
a = np.array([1,0,np.nan,np.inf])
print(np.isnan(a))

[False False  True False]


In [59]:
print(np.isscalar(3.1))
#np.isreal
print(np.iscomplex([1+1j]))
#np.iscomplex
print(np.isreal(15))

True
[ True]
True


In [62]:
np.less()
np.greater_equal()
np.greater()
np.less_equal()
np.equal() #np.allclose pour utilsier une tolérance

TypeError: less() takes from 2 to 3 positional arguments but 0 were given

In [65]:
c = 4
print("%d salut" % c)

4 salut


In [70]:
array = np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [72]:
d = np.arange(50,70,3)

In [75]:
mat = np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
rand_nim = np.random.normal(0,100,15)
print(rand_nim)

[  22.61522466  111.00709151    5.74195571  -66.65306143  -48.67735817
   22.07877153   67.95153678  -28.93914228 -100.16429433  -53.42116535
  -59.46079386  -46.44238176  151.67011759  -97.73725614   61.72286338]


In [85]:
v = np.arange(15,55)
print(v[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [90]:
a = np.arange(10,22).reshape(3,4)
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [92]:
for x in np.nditer(a):
    print(x)

10
11
12
13
14
15
16
17
18
19
20
21


In [95]:
v = np.linspace(5,50,9)
print(v)

[ 5.    10.625 16.25  21.875 27.5   33.125 38.75  44.375 50.   ]


In [98]:
x = np.arange(21)
x[x>=9] = -1
print(x)

[ 0  1  2  3  4  5  6  7  8 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [101]:
x = np.random.randint(0,11,5)
print(x)

[ 8 10  4  0  1]


In [105]:
x = np.arange(5,10)
y = np.arange(5,10)
x*y

array([25, 36, 49, 64, 81])

In [109]:
exercice25 = np.arange(0,10)
exercice25[exercice25 % 2 == 0] = -1
print(exercice25)

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [115]:
u = np.arange(0,9)
u.reshape(3,3) + 202 *np.ones((3,3))

array([[202., 203., 204.],
       [205., 206., 207.],
       [208., 209., 210.]])

In [118]:
m = np.random.randint(0,10,10)
print(m)

[6 5 7 0 0 9 8 1 7 7]


In [124]:
x = np.arange(0,10)
y = np.arange(0,5)
print(np.where(x==y))

(array([], dtype=int64),)


/var/folders/ws/63hgmkhn5cvf2cf7zyfqb64w0000gn/T/ipykernel_1448/1343705090.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(np.where(x==y))


In [125]:
ex30 = np.arange(100).reshape(5,-1)
print(ex30[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
